sudo: required
jdk: openjdk8

services:
  - docker

# Install all dependencies here.
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y graphviz realpath
  - curl -fsSL get.nextflow.io | bash
  - mkdir -p ~/bin
  - cp nextflow ~/bin

# Commands that must run before any tests are executed.
before_script:
  - cp nextflow.config.example nextflow.config

# Commands here should determine whether the build fails or not.
script:
  # Build the images.
  - docker build -t systemsgenetics/gemmaker:latest  Dockerfiles/base/1.0/
  - docker build -t systemsgenetics/fastqc:0.11.7    Dockerfiles/fastqc/0.11.7/
  - docker build -t systemsgenetics/hisat2:2.1.0     Dockerfiles/hisat2/2.1.0/
  - docker build -t systemsgenetics/kallisto:0.45.0  Dockerfiles/kallisto/0.45.0/
  - docker build -t systemsgenetics/python:3.5.1     Dockerfiles/python/3.5.1/
  - docker build -t systemsgenetics/salmon:0.12.0    Dockerfiles/salmon/0.12.0/
  - docker build -t systemsgenetics/samtools:1.9     Dockerfiles/samtools/1.9/
  - docker build -t systemsgenetics/sratoolkit:2.9.2 Dockerfiles/sratoolkit/2.9.2/
  - docker build -t systemsgenetics/stringtie:1.3.4d Dockerfiles/stringtie/1.3.4d/
  - docker build -t systemsgenetics/trimmomatic:0.38 Dockerfiles/trimmomatic/0.38/

  # Push the images.
  # - docker push systemsgenetics/gemmaker:latest
  # - docker push systemsgenetics/fastqc:latest
  # - docker push systemsgenetics/hisat2:2.1.0
  # - docker push systemsgenetics/python:3.5.1
  # - docker push systemsgenetics/samtools:1.9

  # Run the workflow.
  - nextflow run main.nf -profile testing -with-docker
