branches:
  only:
    - issue_38_docker_integration


sudo: required
jdk: openjdk8

services:
  - docker


# Commands which must be executed before installing dependencies.
# before_install:
  # - docker pull systemsgenetics/gemmaker-docker:development


# Install all dependencies here.
# install:
#   - sudo apt-get -qq update
#   - sudo apt-get -qq -y install graphviz realpath
#   - curl -fsSL get.nextflow.io | bash
#   - mkdir -p ~/bin; cp nextflow ~/bin
  # Create a work directory for nextflow, and open up the permissions.
  # - mkdir work/
  # - chmod -R 777 work/


# Commands that must run before any tests are executed.
# before_script:
  # - cp nextflow.config.example nextflow.config


# Commands here should determine whether the build fails or not.
script:
  # Build the images.
  - docker build -t systemsgenetics/gemmaker:latest  Dockerfiles/base/1.0/
  - docker build -t systemsgenetics/fastqc:0.11.7    Dockerfiles/fastqc/0.11.7
  - docker build -t systemsgenetics/hisat2:2.1.0     Dockerfiles/hisat2/2.1.0/
  - docker build -t systemsgenetics/python3:1.0.0    Dockerfiles/python3/1.0.0
  - docker build -t systemsgenetics/samtools:1.9     Dockerfiles/samtools/1.9

  # Push the images.
  - docker push systemsgenetics/gemmaker:latest
  - docker push systemsgenetics/fastqc:latest
  - docker push systemsgenetics/hisat2:2.1.0
  - docker push systemsgenetics/python3:1.0.0
  - docker push systemsgenetics/samtools:1.9

  # Run the workflow.
  # - nextflow run main.nf -with-docker systemsgenetics/gemmaker-docker:development
